[package]
name = "railroad_dsl"
version = "0.1.1"
authors = ["Lukas Lueg <lukas.lueg@gmail.com>"]
license = "MIT"
description = "A small DSL to generate syntax-diagrams"
exclude = ["examples/*.html", "examples/*.jpeg"]
repository = "https://github.com/lukaslueg/railroad_dsl"
readme = "README.md"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
structopt = "0.2.12"
#railroad = "0.1"
#railroad = { git = "https://github.com/birkenfeld/railroad" }
railroad = { path = "../railroad" }
